CREATE DATABASE aa;

USE aa;

CREATE TABLE tr_f_db (
  MERCHANT_ID bigint(20) NOT NULL COMMENT '商户ID',
  DB_NAME varchar(50) NOT NULL COMMENT '数据库名',
  DB_USERNAME varchar(50) NOT NULL COMMENT '用户名',
  DB_PASSWORD varchar(100) NOT NULL COMMENT '用户密码',
  INSTANCE_ID varchar(100) NOT NULL COMMENT '实例ID',
  PROXY_IP varchar(100) NOT NULL COMMENT '应用接入数据库的IP。',
  PROXY_PORT varchar(100) NOT NULL COMMENT '应用端口号',
  STATE char(1) NOT NULL COMMENT '1-空闲；2-在用',
  PRIMARY KEY (MERCHANT_ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '数据库信息';
